server:
  port: 8081

spring:
  application:
    name: department-service

  datasource:
    url: jdbc:mysql://mysql:3306/deptdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
