server:
  port: 8082

spring:
  application:
    name: employee-service
  data:
    mongodb:
      uri: mongodb+srv://bojjaprasanna2022:Hymavathi1234%40@prasannacluster.znz3sl5.mongodb.net/employeeDb?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
